import Link from 'next/link'

export const metadata = { title: 'Terms of Service — ApplyAI' }

export default function TermsPage() {
  const s: Record<string, any> = {
    page: { fontFamily: "'DM Sans', sans-serif", background: '#FBFBF9', minHeight: '100vh' },
    nav: { background: '#0F172A', padding: '0 5vw', height: 56, display: 'flex', alignItems: 'center' },
    wrap: { maxWidth: 700, margin: '0 auto', padding: '48px 20px' },
    h1: { fontSize: 28, fontWeight: 500, marginBottom: 8, letterSpacing: -0.5 },
    updated: { fontSize: 13, color: '#888780', marginBottom: 32 },
    h2: { fontSize: 17, fontWeight: 500, marginTop: 32, marginBottom: 10 },
    p: { fontSize: 14, color: '#444441', lineHeight: 1.7, marginBottom: 12 },
    ul: { fontSize: 14, color: '#444441', lineHeight: 1.7, paddingLeft: 20, marginBottom: 12 },
  }

  return (
    <div style={s.page}>
      <nav style={s.nav}>
        <Link href="/" style={{ color: '#fff', fontWeight: 500, fontSize: 16, textDecoration: 'none' }}>
          Apply<span style={{ color: '#1D9E75' }}>AI</span>
        </Link>
      </nav>
      <div style={s.wrap}>
        <h1 style={s.h1}>Terms of Service</h1>
        <p style={s.updated}>Last updated: June 2026</p>

        <p style={s.p}>
          By using ApplyAI at jobapp.best, you agree to these terms. Please
          read them carefully.
        </p>

        <h2 style={s.h2}>1. The service</h2>
        <p style={s.p}>
          ApplyAI is an AI-powered tool that analyses your CV, searches for
          job vacancies, generates tailored CVs and cover letters, and can
          send job applications on your behalf using your own email account
          if you choose to enable that feature.
        </p>

        <h2 style={s.h2}>2. Your responsibilities</h2>
        <ul style={s.ul}>
          <li>You must provide accurate information in your CV — ApplyAI tailors and reframes your real experience, but does not invent qualifications</li>
          <li>You are responsible for reviewing tailored CVs, cover letters, and recruiter email addresses before they are sent</li>
          <li>If you enable auto-apply, you confirm you have the right to use the email account and app password you provide</li>
          <li>You will not use ApplyAI to submit false, misleading, or fraudulent job applications</li>
        </ul>

        <h2 style={s.h2}>3. AI-generated content</h2>
        <p style={s.p}>
          Tailored CVs, cover letters, and job matches are generated by AI
          (Anthropic's Claude models) based on the CV and preferences you
          provide. While we aim for high quality and accuracy, ApplyAI does
          not guarantee that any application will result in an interview or
          job offer. You should review all generated content before it is
          submitted to an employer.
        </p>

        <h2 style={s.h2}>4. Auto-apply feature</h2>
        <p style={s.p}>
          When you enable auto-apply, ApplyAI sends emails using your own
          email account via an app-specific password. You receive a
          notification for every application sent. You can disable this
          feature and remove your stored credentials at any time from your
          account settings. ApplyAI is not responsible for how a recruiter or
          employer responds to an application sent on your behalf.
        </p>

        <h2 style={s.h2}>5. Subscriptions and billing</h2>
        <ul style={s.ul}>
          <li>The Free plan includes 5 applications per month at no cost</li>
          <li>The Pro plan (£12.99/month) and Global plan (£4.99/month) are billed monthly via Stripe and renew automatically until cancelled</li>
          <li>You can cancel your subscription at any time; you will retain access until the end of the current billing period</li>
          <li>Fees are non-refundable except where required by law</li>
        </ul>

        <h2 style={s.h2}>6. Acceptable use</h2>
        <p style={s.p}>
          You agree not to misuse ApplyAI, including attempting to
          reverse-engineer the service, overload our systems, or use the
          platform for any unlawful purpose.
        </p>

        <h2 style={s.h2}>7. Limitation of liability</h2>
        <p style={s.p}>
          ApplyAI is provided "as is" without warranties of any kind. We are
          not liable for any indirect, incidental, or consequential damages
          arising from your use of the service, including missed job
          opportunities or employer responses to submitted applications.
        </p>

        <h2 style={s.h2}>8. Changes to the service</h2>
        <p style={s.p}>
          We may update, modify, or discontinue features of ApplyAI at any
          time. We will provide reasonable notice of material changes that
          affect your use of the service.
        </p>

        <h2 style={s.h2}>9. Governing law</h2>
        <p style={s.p}>
          These terms are governed by the laws of the United Kingdom.
        </p>

        <h2 style={s.h2}>10. Contact</h2>
        <p style={s.p}>
          Questions about these terms? Email us at{' '}
          <a href="mailto:support@jobapp.best" style={{ color: '#1D9E75' }}>support@jobapp.best</a>.
        </p>
      </div>
    </div>
  )
}
